services:
    mongodb:
        image: mongo:6.0
        container_name: mongodb_dev
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: develop
            MONGO_INITDB_ROOT_PASSWORD: develop
        volumes:
            - mongo_data:/data/db

    mongo-express:
        image: mongo-express
        container_name: mongo_express_dev
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: develop
            ME_CONFIG_MONGODB_ADMINPASSWORD: develop
            ME_CONFIG_MONGODB_URL: mongodb://develop:develop@mongodb:27017/
        depends_on:
            - mongodb

volumes:
    mongo_data:
