services:
    mongodb_test:
        image: mongo:6.0
        container_name: mongodb_test
        restart: always
        ports:
            - 27018:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: tester
            MONGO_INITDB_ROOT_PASSWORD: tester
